services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: power_tracker
      POSTGRES_USER: ${POSTGRES_DEFAULT_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_DEFAULT_PASS:-change_me_postgres}
    volumes:
      - postgres_data_powertracker:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-pt_rabbitmq}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-change_me_rabbitmq}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data_powertracker:
  rabbitmq_data:
